name: Install Tools & Dependencies
description: Installs Bun & package dependencies

runs:
  using: composite
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v2

    - name: Cache dependencies and Next.js build
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
          ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-

    - name: Install dependencies
      run: bun install
      shell: bash
